---
  - name: JAVA 8 - install Java 1.8 for CeontOS 7
    yum:
      name: java-1.8.0-openjdk
      state: installed
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
    register: java8_result

#  - debug:
#      var: jenkins_result

#  - debug:
#      var: hostvars